version: '3.6'
services:

  setup_elasticsearch:
    image: elasticsearch:${TAG}
    container_name: setup_elasticsearch
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-elasticsearch.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-elasticsearch.sh:/usr/local/bin/setup-elasticsearch.sh:ro'

  setup_es02:
    image: elasticsearch:${TAG}
    container_name: setup_es02
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-es02.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    depends_on: ['elasticsearch']
    volumes:
      - './config:/config'
      - './scripts/setup-es02.sh:/usr/local/bin/setup-es02.sh:ro'
  
  setup_es03:
    image: elasticsearch:${TAG}
    container_name: setup_es03
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-elasticsearch.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    depends_on: ['elasticsearch']
    volumes:
      - './config:/config'
      - './scripts/setup-es03.sh:/usr/local/bin/setup-elasticsearch.sh:ro'

  setup_kibana:
    image: kibana:${TAG}
    container_name: setup_kibana
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro'
      - './config/ssl/ca/ca.crt:/usr/share/kibana/config/ca/ca.crt'
    depends_on: ['elasticsearch', 'es02', 'es03']
    #depends_on: ['elasticsearch']
    networks: ['docker_elk']

  setup_logstash:
    image: logstash:${TAG}
    container_name: setup_logstash
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-logstash.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-logstash.sh:/usr/local/bin/setup-logstash.sh:ro'
      - './config/ssl/ca/ca.crt:/usr/share/logstash/config/ca/ca.crt'
    depends_on: ['elasticsearch']
    networks: ['docker_elk']
