

pipeline.workers: '12'
pipeline.batch.size: '30000'
pipeline.batch.delay: '50'
config.reload.automatic: 'true'
config.reload.interval: '10s'
xpack.monitoring.enabled: 'true'
http.host: 0.0.0.0
# read password from logstash.keystore
xpack.monitoring.elasticsearch.password: ${ELASTIC_PASSWORD}
xpack.monitoring.elasticsearch.url: https://elasticsearch:9200
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.ssl.ca: /usr/share/logstash/config/certs/ca/ca.crt

